//  Created by TagCommander on 29/07/2016.
//  Version : 4.0.2016-07-29
//
//  Copyright (c) 2016 TagCommander. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __GENERATED_H__
#define __GENERATED_H__

extern NSString *const kTCTagCommanderVersion;
extern NSString *const kTCTagCommanderMarketingVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;

extern NSString *const kTCReleaseClientName;



#endif //__GENERATED_H__
